const DEFAULT_PRODUCTS=[{name:'자숙 대게 (프리미엄)',desc:'살이 꽉 찬 프리미엄 대게',price:'₩89,000~',badge:'BEST',image:''},{name:'자숙 홍게',desc:'부드럽고 깊은 풍미의 홍게',price:'₩49,000~',badge:'추천',image:''},{name:'대게+홍게 세트',desc:'대게와 홍게를 한 번에 즐기는 구성',price:'₩129,000~',badge:'SET',image:''},{name:'대게 다리살 (자숙)',desc:'간편하게 즐기는 대게 다리살',price:'₩59,000~',badge:'NEW',image:''}];
const grid=document.getElementById('editorGrid');
const getProducts=()=>{try{const v=JSON.parse(localStorage.getItem('badaProducts'));return Array.isArray(v)&&v.length?v:structuredClone(DEFAULT_PRODUCTS)}catch(e){return structuredClone(DEFAULT_PRODUCTS)}};
let products=getProducts();
function render(){grid.innerHTML='';products.forEach((p,i)=>{const card=document.createElement('section');card.className='card';card.innerHTML=`<h2>상품 ${i+1}</h2><div class="preview">${p.image?`<img src="${p.image}" alt="미리보기">`:'사진 미등록'}</div><div class="field"><label>상품명</label><input data-k="name" data-i="${i}" value="${esc(p.name)}"></div><div class="field"><label>설명</label><textarea data-k="desc" data-i="${i}">${esc(p.desc)}</textarea></div><div class="field"><label>가격</label><input data-k="price" data-i="${i}" value="${esc(p.price)}"></div><div class="field"><label>배지</label><input data-k="badge" data-i="${i}" value="${esc(p.badge)}"></div><div class="field"><label>상품 사진</label><input type="file" accept="image/*" data-file="${i}"></div>`;grid.appendChild(card)});bind()}
function bind(){document.querySelectorAll('[data-k]').forEach(el=>el.addEventListener('input',e=>{products[+e.target.dataset.i][e.target.dataset.k]=e.target.value}));document.querySelectorAll('[data-file]').forEach(el=>el.addEventListener('change',e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>1500000){alert('이미지는 1.5MB 이하로 올려주세요.');e.target.value='';return}const r=new FileReader();r.onload=()=>{products[+e.target.dataset.file].image=r.result;render()};r.readAsDataURL(f)}))}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
document.getElementById('saveBtn').onclick=()=>{localStorage.setItem('badaProducts',JSON.stringify(products));alert('저장했습니다. 같은 브라우저에서 사이트를 열면 반영됩니다.')};
document.getElementById('resetBtn').onclick=()=>{if(confirm('상품 정보를 기본값으로 복원할까요?')){products=structuredClone(DEFAULT_PRODUCTS);localStorage.removeItem('badaProducts');render()}};
render();
